version: "3"

services:
  web:
    image: "eduardobitar/myfirstapp:3.0"
    networks:
      labdocker:
        ipv4_address: 172.20.0.2
    ports:
      - "80:80"
    environment:
      MESSAGE: 'Ol√° visitante! Desafio cumprido...'

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/srv/redis/data:/data"
    command: "redis-server --appendonly yes"
    networks:
      labdocker:
        ipv4_address: 172.20.0.3

networks:
  labdocker:
    ipam:
      config:
        - subnet: 172.20.0.0/24
